-- 用户表
DROP TABLE IF EXISTS "user";
CREATE TABLE "user" (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  deleted SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_username UNIQUE (username)
);

-- 系统设置表
DROP TABLE IF EXISTS system_setting;
CREATE TABLE system_setting (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(50) NOT NULL,
  setting_value CLOB,
  description VARCHAR(200),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_setting_key UNIQUE (setting_key)
);

-- 轮播图表
DROP TABLE IF EXISTS banner;
CREATE TABLE banner (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  image_url VARCHAR(200) NOT NULL,
  link_url VARCHAR(200),
  sort INT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  deleted SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 视频表
DROP TABLE IF EXISTS video;
CREATE TABLE video (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description CLOB,
  cover_url VARCHAR(200),
  video_url VARCHAR(200) NOT NULL,
  duration INT NOT NULL DEFAULT 0,
  views INT NOT NULL DEFAULT 0,
  category VARCHAR(50),
  status SMALLINT NOT NULL DEFAULT 1,
  deleted SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 系统日志表
DROP TABLE IF EXISTS system_log;
CREATE TABLE system_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(20) NOT NULL,
  username VARCHAR(50) NOT NULL,
  action VARCHAR(200) NOT NULL,
  ip VARCHAR(50),
  user_agent VARCHAR(500),
  params CLOB,
  result CLOB,
  error CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 